### ISSUE TITLE
UMD in npm

### ISSUE THREAD

**Issue by Kal-Aster** [riot/lazy#5]
Is it possible to add an UMD bundle in the npm package?

I saw that there is the configuration for it via rollup in the repository, but neither the config is in the npm package.

I know it is quite useless for production purposes, but I found my self in the need of the umd bundle of this library for testing a library

Thanks!

**Comment by GianlucaGuarini** [comment]
https://unpkg.com/@riotjs/lazy@1.0.1/lazy.js please check it better ;)

**Comment by Kal-Aster** [comment]
It is not in the folder after I do `npm install @riotjs/lazy`...

**Comment by Kal-Aster** [comment]
Ok, it was beacuse I used `npm install riot/lazy`... Thank you
